#!/bin/bash -e
#
# Azouk Libraries -- Libraries and goodies created for www.azouk.com.
# Copyright (C) 2008-2009 Azouk Network Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author:
#      Piotr Findeisen <piotr.findeisen at gmail.com>
#

if [ $# -ne 1 ]; then
    echo "Usage: $0 <version-bash-file>" >&2
    exit 1
fi

VERSION_BASH_FILE="$1"; shift

git describe --always 2>/dev/null | grep -qE . || exit 1
version=`git describe --always`
git update-index -q --refresh
test -z "$(git diff-index --name-only HEAD --)" || version="$version-dirty"
version="$(echo "$version" | sed -e 's/-/./g' | sed -e 's/^v//')"
version_hash="$(echo $version | sha1sum - | cut -d' ' -f1)"
{
    echo "version=\"$version\""
    echo "version_hash=\"$version_hash\""
    echo "version_short_hash=\"${version_hash:0:7}\""
} > $VERSION_BASH_FILE.tmp

{ test -f $VERSION_BASH_FILE && cmp $VERSION_BASH_FILE $VERSION_BASH_FILE.tmp >/dev/null; } || \
    mv $VERSION_BASH_FILE.tmp $VERSION_BASH_FILE
